name: Java & Node.js CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  java_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'  

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build with Maven
        working-directory: backend  # Set the correct working directory for Maven
        run: mvn clean install

  node-build:
    name: Node.js Build
    runs-on: ubuntu-latest
    needs: java_build  # Ensure Node.js build runs after Java build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # You only need this if you need the code in this job

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend  # Ensure dependencies are installed in the correct directory
        run: npm install

      - name: Run build
        working-directory: frontend  # Ensure build runs in the correct directory
        run: npm run build