name: Java & Node.js CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build with Maven
        working-directory: backend
        run: mvn clean install -DskipTests

      - name: Archive Java artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: backend/target/my-app.jar  # Specific JAR name

  node-build:
    runs-on: ubuntu-latest
    needs: java-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run build
        working-directory: frontend
        run: npm run build

      - name: Archive frontend build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build

  docker-build-push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: [java-build, node-build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-buildx-

      - name: Check Docker secrets
        run: |
          echo "Checking if Docker secrets are set..."
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is missing!"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKER_ACCESS_TOKEN }}" ]; then
            echo "DOCKER_ACCESS_TOKEN is missing!"
            exit 1
          fi
          echo "Secrets are set correctly."

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build frontend Docker image
        working-directory: frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-frontend-app:latest .
          docker images

      - name: Build backend Docker image
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-backend-app:latest .
          docker images

      - name: Push frontend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/your-frontend-app:latest

      - name: Push backend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/your-backend-app:latest